### ISSUE TITLE
Stale bot

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/.github#3]
Set up [a stale bot](https://github.com/probot/stale) to automatically tag issues as stale, allowing us to triage issues that have stagnated.

**Comment by kimburgess** [comment]
Rather than the external bot, we can use [actions/stale](https://github.com/actions/stale) for this.

It's intended to be setup locally in each repo, but to DRY things up it should be possible to override the [env var it pulls repo context from](https://github.com/actions/toolkit/blob/4dd900dde00dcc90e5c649b688c643b1fc7684a2/packages/github/src/context.ts#L59), centrally define one config here and then iterate over all of our repos as a [jobs matrix](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).

We can pull a list of these via a similar approach to the [label sync action](https://github.com/PlaceOS/.github/blob/57040209be7d2f6df79beda4ee92960d5e269ad5/.github/workflows/org-labels.yml#L54-L65).

**Comment by caspiano** [comment]
Current processes are adequate in identifying residual/stale issues.
